### ISSUE TITLE
How to import all .graphql files in one for easy import

### ISSUE THREAD

**Issue by sanket-work** [ardatan/graphql-import-node#10]
Is there a way to club all .graphql files in one single file and later import the single file wherever required.
In the  _node_modules/graphql-import-node/register.d.ts_ I do see a module named `*.graphqls `but no associated documentation.

**Comment by ardatan** [comment]
`*.graphqls`doesn't stand for `graphql in plural` but `graphql schema`.
https://github.com/ardatan/graphql-toolkit#-file-loading-for-both-schema-and-resolvers
I recommend you to use something like this to load multiple files at once easily.
