### ISSUE TITLE
Cannot set property '.graphql' of undefined after Webpack build 

### ISSUE THREAD

**Issue by doryanB** [ardatan/graphql-import-node#14]
Hi,  
I'm trying to build my project with webpack. 
Everything is good but when i'm running my project , i see that error 

```
webpack-internal:///./node_modules/graphql-import-node/register.js:13
  (void 0)[`.${ext}`] = handleModule;
  ``` 
  
  do you have a clue on what is going on ? 
  thank you for your time :)

**Comment by ardatan** [comment]
`graphql-import-node` is not compatible with bundlers like Webpack, Rollup or Parcel. I recommend you to use webpack loaders to load graphql files.
