### ISSUE TITLE
Update readme with 'dynamicImport' Babel dependency

### ISSUE THREAD

**Issue by plummer-flex** [ardatan/graphql-import-node#3]
`npm i @babel/plugin-syntax-dynamic-import --save-dev`

**.babelrc**
```
{
 ...
  "plugins": ["@babel/plugin-syntax-dynamic-import"]
}
```

**Comment by ardatan** [comment]
This plugin isn't for Babel, it is a runtime plugin for NodeJS environment.

**Comment by plummer-flex** [comment]
so then min node version is 9.x?
