### ISSUE TITLE
typescript is not compiling without "import 'graphql-import-node';"

### ISSUE THREAD

**Issue by furozen** [ardatan/graphql-import-node#9]
typescript is not compiling without "import 'graphql-import-node';"

I added "graphql-import-node" to package.json 

but IDE redlined "import * as schema from './schema.graphql'"
till I added import 'graphql-import-node'; to index.ts
so please update readme.ts

**Comment by ardatan** [comment]
@furozen It's already written there;
https://github.com/ardatan/graphql-import-node#usage-with-node-javascript
But I added it again in TypeScript section.
